using System;
using System.Collections;
using GeneXus.Utils;
using GeneXus.Resources;
using GeneXus.Application;
using GeneXus.Metadata;
using GeneXus.Cryptography;
using com.genexus;
using GeneXus.Data.ADO;
using GeneXus.Data.NTier;
using GeneXus.Data.NTier.ADO;
using GeneXus.WebControls;
using GeneXus.Http;
using GeneXus.Procedure;
using GeneXus.XML;
using GeneXus.Search;
using GeneXus.Encryption;
using GeneXus.Http.Client;
using System.Threading;
using System.Xml.Serialization;
using System.Runtime.Serialization;
namespace GeneXus.Programs {
   public class aempleado_dataprovider : GXProcedure
   {
      public static int Main( string[] args )
      {
         return new aempleado_dataprovider().MainImpl(args); ;
      }

      public int executeCmdLine( string[] args )
      {
         return ExecuteCmdLine(args); ;
      }

      protected override int ExecuteCmdLine( string[] args )
      {
         GXBCCollection<SdtEmpleado> aP0_Gxm2rootcol = new GXBCCollection<SdtEmpleado>()  ;
         execute(out aP0_Gxm2rootcol);
         return GX.GXRuntime.ExitCode ;
      }

      public aempleado_dataprovider( )
      {
         context = new GxContext(  );
         DataStoreUtil.LoadDataStores( context);
         IsMain = true;
         context.SetDefaultTheme("parques", true);
      }

      public aempleado_dataprovider( IGxContext context )
      {
         this.context = context;
         IsMain = false;
      }

      public void execute( out GXBCCollection<SdtEmpleado> aP0_Gxm2rootcol )
      {
         this.Gxm2rootcol = new GXBCCollection<SdtEmpleado>( context, "Empleado", "parques") ;
         initialize();
         ExecuteImpl();
         aP0_Gxm2rootcol=this.Gxm2rootcol;
      }

      public GXBCCollection<SdtEmpleado> executeUdp( )
      {
         execute(out aP0_Gxm2rootcol);
         return Gxm2rootcol ;
      }

      public void executeSubmit( out GXBCCollection<SdtEmpleado> aP0_Gxm2rootcol )
      {
         this.Gxm2rootcol = new GXBCCollection<SdtEmpleado>( context, "Empleado", "parques") ;
         SubmitImpl();
         aP0_Gxm2rootcol=this.Gxm2rootcol;
      }

      protected override void ExecutePrivate( )
      {
         /* GeneXus formulas */
         /* Output device settings */
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 101";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000001";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.rodríguez1@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 102";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000002";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.martínez2@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 103";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000003";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.martínez3@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 104";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000004";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.díaz4@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 105";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000005";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.rodríguez5@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 106";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000006";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.pérez6@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 107";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000007";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.ramírez7@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 108";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000008";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.sánchez8@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 109";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000009";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.rodríguez9@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 110";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000010";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.ramírez10@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 111";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000011";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.gómez11@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 112";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000012";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.díaz12@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 113";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000013";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.rodríguez13@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 114";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000014";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.lópez14@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 115";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000015";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.díaz15@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 116";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000016";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.fernández16@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 117";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000017";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.torres17@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 118";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000018";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.pérez18@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 119";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000019";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.lópez19@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 120";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000020";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.díaz20@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 121";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000021";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.pérez21@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 122";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000022";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.fernández22@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 123";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000023";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.sánchez23@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 124";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000024";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.pérez24@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 125";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000025";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.torres25@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 126";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000026";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.lópez26@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 127";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000027";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.fernández27@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 128";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000028";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.lópez28@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 129";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000029";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.ramírez29@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 130";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000030";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.lópez30@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 131";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000031";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.ramírez31@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 132";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000032";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.fernández32@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 133";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000033";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.sánchez33@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 134";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000034";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.lópez34@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 135";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000035";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.fernández35@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 136";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000036";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.gómez36@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 137";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000037";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.sánchez37@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 138";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000038";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.martínez38@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 139";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000039";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.sánchez39@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 140";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000040";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.gómez40@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 141";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000041";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.sánchez41@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 142";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000042";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.díaz42@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 143";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000043";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.gómez43@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 144";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000044";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.fernández44@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 145";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000045";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.rodríguez45@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 146";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000046";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.rodríguez46@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 147";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000047";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.díaz47@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 148";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000048";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.gómez48@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 149";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000049";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.pérez49@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 150";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000050";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.díaz50@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 151";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000051";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.torres51@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 152";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000052";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.rodríguez52@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 153";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000053";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.martínez53@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 154";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000054";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.rodríguez54@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 155";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000055";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.martínez55@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 156";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000056";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.torres56@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 157";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000057";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.fernández57@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 158";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000058";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.lópez58@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 159";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000059";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.pérez59@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 160";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000060";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.torres60@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 161";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000061";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.martínez61@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 162";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000062";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.ramírez62@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 163";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000063";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.díaz63@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 164";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000064";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.díaz64@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 165";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000065";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.martínez65@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 166";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000066";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.ramírez66@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 167";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000067";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.torres67@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 168";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000068";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.rodríguez68@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 169";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000069";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.torres69@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Martínez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 170";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000070";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.martínez70@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 171";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000071";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.rodríguez71@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 172";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000072";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.sánchez72@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Ana";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 173";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000073";
         Gxm1empleado.gxTpr_Empleadoemail = "ana.pérez73@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 174";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000074";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.rodríguez74@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 175";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000075";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.díaz75@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 176";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000076";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.sánchez76@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 177";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000077";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.rodríguez77@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 178";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000078";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.ramírez78@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 179";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000079";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.rodríguez79@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Laura";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 180";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000080";
         Gxm1empleado.gxTpr_Empleadoemail = "laura.gómez80@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 181";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000081";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.lópez81@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 182";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000082";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.lópez82@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 183";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000083";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.sánchez83@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 184";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000084";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.díaz84@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Diego";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 185";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000085";
         Gxm1empleado.gxTpr_Empleadoemail = "diego.rodríguez85@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 186";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000086";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.torres86@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 187";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000087";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.gómez87@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Rodríguez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 188";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000088";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.rodríguez88@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Torres";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 189";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000089";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.torres89@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Pedro";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 190";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000090";
         Gxm1empleado.gxTpr_Empleadoemail = "pedro.gómez90@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Camila";
         Gxm1empleado.gxTpr_Empleadoapellido = "Sánchez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 191";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000091";
         Gxm1empleado.gxTpr_Empleadoemail = "camila.sánchez91@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 192";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000092";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.gómez92@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 193";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000093";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.fernández93@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Marcos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Ramírez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 194";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000094";
         Gxm1empleado.gxTpr_Empleadoemail = "marcos.ramírez94@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Carlos";
         Gxm1empleado.gxTpr_Empleadoapellido = "Pérez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 195";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000095";
         Gxm1empleado.gxTpr_Empleadoemail = "carlos.pérez95@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 196";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000096";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.díaz96@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "López";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 197";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000097";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.lópez97@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Juan";
         Gxm1empleado.gxTpr_Empleadoapellido = "Gómez";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 198";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000098";
         Gxm1empleado.gxTpr_Empleadoemail = "juan.gómez98@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Sofía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Fernández";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 199";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000099";
         Gxm1empleado.gxTpr_Empleadoemail = "sofía.fernández99@ejemplo.com";
         Gxm1empleado = new SdtEmpleado(context);
         Gxm2rootcol.Add(Gxm1empleado, 0);
         Gxm1empleado.gxTpr_Empleadonombre = "Lucía";
         Gxm1empleado.gxTpr_Empleadoapellido = "Díaz";
         Gxm1empleado.gxTpr_Empleadodireccion = "Calle Falsa 200";
         Gxm1empleado.gxTpr_Empleadotelefono = "3874000100";
         Gxm1empleado.gxTpr_Empleadoemail = "lucía.díaz100@ejemplo.com";
         cleanup();
      }

      public override void cleanup( )
      {
         CloseCursors();
         if ( IsMain )
         {
            context.CloseConnections();
         }
         ExitApp();
      }

      public override void initialize( )
      {
         Gxm1empleado = new SdtEmpleado(context);
         /* GeneXus formulas. */
      }

      private GXBCCollection<SdtEmpleado> Gxm2rootcol ;
      private SdtEmpleado Gxm1empleado ;
      private GXBCCollection<SdtEmpleado> aP0_Gxm2rootcol ;
   }

}
